### ISSUE TITLE
Is gpttools supported by rstudio server?

### ISSUE THREAD

**Issue by HeyLifeHD** [JamesHWade/gpttools#14]
When trying to run gpttools on an Rstudio server, I get following message:

`> gpttools::script_to_function_addin()
✓ API already validated in this session.
Error: 'selectionGet' is not an exported object from 'namespace:rstudioapi'`

Does gpttools currently support Rstudio server?

Thanks a lot in advance.

Best,

Joschka

**Comment by JamesHWade** [comment]
Hmmm... that's an odd error. `selectionGet` is part of rstudioapi. Maybe try updating to the latest version of rstudioapi? What version of RStudio Server are you using? I was able to get it working in RStudio Cloud, which is running RStudio Workbench.

**Comment by MichelNivard** [comment]
You can run these checks as well to see if anything is up with rstudioapi:
 # Returns T/F
rstudioapi::[isAvailable](https://rstudio.github.io/rstudioapi/reference/isAvailable.html)()
# Returns error if not available
rstudioapi::[verifyAvailable](https://rstudio.github.io/rstudioapi/reference/isAvailable.html)()

**Comment by JamesHWade** [comment]
I like the idea of adding in some error handling using `isAvailable()`.  It looks like their built-in version checks don't work with their new versioning system though.

**Comment by HeyLifeHD** [comment]
I think it was a version problem. With the newest R version, it seems to be working. 
Thank you,

Joschka

**Comment by JamesHWade** [comment]
Thank you for the follow up and glad to hear it's now working!
