### ISSUE TITLE
Enhancement via dm

### ISSUE THREAD

**Issue by MichelNivard** [JamesHWade/gpttools#16]
This came via Twitter dm:

“Hi Michel, I'm very excited about your GPT packages for R, which look amazing. I have a question if you don't mind: do you know a way to apply chat GPT's prompts to a dataset? For instance, I have a dataset with a variable with long texts. I'd like to summarize all of them (e.g., in a sentence) with chat GPT. I've checked your packages, but I'm unsure if one can apply the prompt to an entire dataset. Any thoughts would be really useful”

gptapply()?

not an addin so serious mission creep (I sugested the api directly for now)

**Comment by JamesHWade** [comment]
This is a bit out of scope for now. Happy to reconsider if there's persistent interest.
