### ISSUE TITLE
feature request roxygen for data files

### ISSUE THREAD

**Issue by higgi13425** [JamesHWade/gpttools#3]
For data files, build a reasonable roxygen file for each data field for the help file.

**Comment by JamesHWade** [comment]
Good idea, @higgi13425! Can you provide a few examples of what you're after? If you have some successful prompts, those would be a great starting point.

**Comment by higgi13425** [comment]
The {medicaldata} package has several (by hand) examples. https://github.com/higgi13425/medicaldata

**Comment by higgi13425** [comment]
After installing the package, you can run help("dataset") to see the output.
The extra stuff has to be done by hand, but the details on each variable would be nice to automate.

**Comment by higgi13425** [comment]
Basically the core chunk for everything in the 'man' file,
like this:
\title{Diabetes Prediction Dataset from the Pima Indian Tribe and the NIDDK}
\format{
A data frame with 768 observations on 9 variables, with significant missing data for some predictor variables.
\describe{
\item{pregnancy_num}{number of pregnancies from 0 to 17; type: double}
\item{glucose_mg-dl}{Plasma glucose concentration at 2 hours after administration of an oral glucose tolerance test in mg/deciliter, from 44 to 199, 5 missing; type: double}
\item{dbp_mm-hg}{diastolic blood pressure in millimeters of mercury (mm Hg), the second number reported in blood pressure, from 24 to 122, 35 missing; type: double}
\item{triceps_mm}{triceps skin fold thickness in mm, a measure of subcutaneous fat, from 7 to 99, 227 missing; type: double}
\item{insulin_microiu-ml}{serum insulin at 2 hours after administration of an oral glucose tolerance test in microIU per milliliter (IU is international units), from 14 to 846, 374 missing; type: double}
\item{bmi}{body mass index, in kg of weight per meters of height squared, from 18.2 to 67.1, 11 missing; type: double}
\item{pedigree}{a diabetes pedigree score, with points added for each additional relative with diabetes, weighted for the closeness of their genetic relation to the participant, from 0.78 to 2.42. Zero missing; type: double}
\item{age}{Age in years, from 21 to 81, Zero missing; type: double}
\item{diabetes_5y}{Diagnosis of diabetes in the following 5 years - pos or neg, 268 pos, Zero missing; type: factor}
}

**Comment by JamesHWade** [comment]
Ahhh... very interesting. This might take a little work but I like the idea! My initial thought is to feed the model a few rows of the data set. That will probably require an interactive addin. Great suggestion!

**Comment by higgi13425** [comment]
I think so - I look at the dataset (usually not that big, as CRAN limits sizes), and use that to hand write these with total N, mean and range for items, etc.

**Comment by MichelNivard** [comment]
One issue here is that inevitably people will run this on data that should not be shared with an AI (GDPR/consent/privacy/medical data etc), so perhaps if we make this a function actual Run things like summary() and alternatives of that on the data and send THAT to OpenAI?

**Comment by JamesHWade** [comment]
Oh, I hadn't even thought of that @MichelNivard. Thank you for the reminder. With a bit of luck, my implementation in #4 did data summarization before passing to OpenAI. I'm merge this in once the checks pass.

**Comment by JamesHWade** [comment]
@higgi13425, please give it a try! I'm certainly interested in your feedback!

**Comment by higgi13425** [comment]
I tried the cytomegalovirus dataset, which I loaded to the named data.frame cmv.
I used skimr, with temp 0.7 and 887 tokens
and got what looks like pythonic output:

#!/usr/bin/env python
# -*- coding: utf-8 -*-

# @Filename: step3_generate_result_summary
# @Date: 2017-02-14
# @Author: Mark Wang
# @Email: wangyouan@gmial.com


import os

import pandas as pd

from xvfbwrapper import Xvfb

from ..report_generator.constant import Constant as const

from ..report_generator.report_generator import ReportGenerator

from ...common import FilePath


def generate_result_summary(trading_days, result_path, report_path):
    if not os.path.isdir(report_path):
        os.makedirs(report_path)

    vdisplay = Xvfb()
    vdisplay.start()

    report_file_name = os.path.join(report_path, 'result_table.xlsx')
    report_generator = ReportGenerator(report_file_name)
    report_generator.write_title(const.RESULT_SUMMARY_TITLE)

    report_generator.write_header(const.RESULT_SUMMARY_HEADER)

    result_summary = pd.DataFrame()

    for t_day in trading_days:
        t_day_str = '{}_{}'.format(t_day.year, t_day.month)

        result_file_name = os.path.join(result_path, '{}.p'.format(t_day_str))

        if not os.path.isfile(result_file_name):
            continue

        result_info = pd.read_pickle(result_file_name)
        result_info = result_info.reset_index()
        result_info = result_info.set_index(const.RESULT_SUMMARY_INDEX)
        result_info.loc[:, const.RESULT_SUMMARY_REPORT_DATE] = t_day_str
        result_summary = result_summary.append(result_info)

    result_summary = result_summary.reset_index()
    report_generator.write_table(result_summary)

    report_generator.close_workbook()
    vdisplay.stop()


if __name__ == '__main__':
    trading_days = pd.date_range('20160101', '20170214')
    generate_result_summary(trading_days, FilePath.REPORT_DATA_PATH, FilePath.REPORT_RESULT_PATH)

**Comment by higgi13425** [comment]
I tried the cytomegalovirus dataset, which I loaded to the named data.frame cmv.
I used glimpse, with temp 0.36 and 887 tokens
and got R output , though the N (15) is wrong - 64 rows of 26 vars

 #' Patient Data

#' This data set contains patient data for 15 patients.

#' @format A data frame with 15 rows and 16 variables:
#' \describe{
#'   \item{ID}{Numeric. Patient ID.}
#'   \item{age}{Numeric. Patient age.}
#'   \item{sex}{Numeric. Patient sex (0 = Female, 1 = Male).}
#'   \item{race}{Numeric. Patient race (0 = White, 1 = Other).}
#'   \item{diagnosis}{Character. Patient diagnosis.}
#'   \item{diagnosis.type}{Numeric. Patient diagnosis type (0 = Non-Hodgkin Lymphoma, 1 = Other).}
#'   \item{time.to.transplant}{Numeric. Time to transplant (days). Range: 2.43 - 92.71. Missing values: 1.}
#'   \item{prior.radiation}{Numeric. Prior radiation (0 = No, 1 = Yes).}
#'   \item{prior.chemo}{Numeric. Prior chemo (0 - 4). Range: 0 - 4. Missing values: 1.}
#'   \item{prior.transplant}{Numeric. Prior transplant (0 = No, 1 = Yes).}
#'   \item{recipient.cmv}{Numeric. Recipient CMV (0 = No, 1 = Yes).}
#'   \item{donor.cmv}{Numeric. Donor CMV (0 = No, 1 = Yes).}
#'   \item{donor.sex}{Numeric. Donor sex (0 = Female, 1 = Male).}
#'   \item{TNC.dose}{Numeric. TNC dose (in millions). Range: 4.26 - 21.02.}
#'   \item{CD34.dose}{Numeric. CD34 dose (in millions). Range: 2.04 - 7.00.}
#'   \item{CD3.dose}{Numeric. CD3 dose (in millions). Range: 2.19 - 7.27. Missing values: 2.}
#'   \item{CD8.dose}{Numeric. CD8 dose (in millions). Range: 0.17 - 2.48. Missing values: 2.}
#'   \item{TBI.dose}{Numeric. TBI dose (in cGy). Range: 200 - 400.}
#'   \item{C1/C2}{Numeric. C1/C2 (0 = C1, 1 = C2).}
#'   \item{aKIRs}{Numeric. aKIRs (1 - 6). Range: 1 - 6.}
#'   \item{cmv}{Numeric. CMV (0 = No, 1 = Yes).}
#'   \item{time.to.cmv}{Numeric. Time to CMV (days). Range: 0.69 - 65.12.}
#'   \item{agvhd}{Numeric. Acute GVHD (0 = No, 1 = Yes).}
#'   \item{time.to.agvhd}{Numeric. Time to AGVHD (days). Range: 0 - 65.12. Missing values: 1.}
#'   \item{cgvhd}{Numeric. Chronic GVHD (0 = No, 1 = Yes).}
#'   \item{time.to.cgvhd}{Numeric. Time to CGVHD (days). Range: 0 - 65.12. Missing values: 1.}
#' }

**Comment by higgi13425** [comment]
This is imperfect, but quite nice - a bit help when there are many variables.

**Comment by higgi13425** [comment]
I tried the cytomegalovirus dataset, which I loaded to the named data.frame cmv.
I used summary, with temp 0.36 and 995 tokens
and got R output , though the N (64) is right, but 16 vars is wrong (actually 26 vars)

#' Transplant Data

#' This dataset contains information about 64 heart transplant patients.

#' @format A data frame with 64 observations on the following 16 variables.
#' \describe{
#'   \item{ID}{A unique identifier for each patient, numeric.}
#'   \item{age}{Age of the patient at the time of transplant, numeric.}
#'   \item{sex}{Gender of the patient, 0 = male, 1 = female, numeric.}
#'   \item{race}{Race of the patient, 0 = white, 1 = black, numeric.}
#'   \item{diagnosis}{Diagnosis of the patient, character.}
#'   \item{diagnosis.type}{Type of diagnosis, 0 = primary, 1 = secondary, numeric.}
#'   \item{time.to.transplant}{Time from diagnosis to transplant, numeric.}
#'   \item{prior.radiation}{Whether the patient had prior radiation therapy, 0 = no, 1 = yes, numeric.}
#'   \item{prior.chemo}{Number of prior chemotherapy treatments, numeric.}
#'   \item{prior.transplant}{Whether the patient had a prior transplant, 0 = no, 1 = yes, numeric.}
#'   \item{recipient.cmv}{Whether the recipient was CMV positive, 0 = no, 1 = yes, numeric.}
#'   \item{donor.cmv}{Whether the donor was CMV positive, 0 = no, 1 = yes, numeric.}
#'   \item{donor.sex}{Gender of the donor, 0 = male, 1 = female, numeric.}
#'   \item{TNC.dose}{Dose of TNC cells, numeric.}
#'   \item{CD34.dose}{Dose of CD34 cells, numeric.}
#'   \item{CD3.dose}{Dose of CD3 cells, numeric.}
#'   \item{CD8.dose}{Dose of CD8 cells, numeric.}
#'   \item{TBI.dose}{Dose of total body irradiation, numeric.}
#'   \item{C1/C2}{Whether the patient was C1 or C2, 0 = C1, 1 = C2, numeric.}
#'   \item{aKIRs}{Number of activating KIRs, numeric.}
#'   \item{cmv}{Whether the patient had CMV infection, 0 = no, 1 = yes, numeric.}
#'   \item{time.to.cmv}{Time to CMV infection, numeric.}
#'   \item{agvhd}{Whether the patient had acute GVHD, 0 = no, 1 = yes, numeric.}
#'   \item{time.to.agvhd}{Time to acute GVHD, numeric.}
#'   \item{cgvhd}{Whether the patient had chronic GVHD, 0 = no, 1 = yes, numeric.}
#'   \item{time.to.cgvhd}{Time to chronic GVHD, numeric.}
#' }
#' 
#' @source \url{https://www.kaggle.com/cdabakoglu/heart-transplant-survival-data}
#' 
#' @name transplant
#' 
#' @note Range, number of missing values, and type for each column in the data frame:
#' 
#' ID             Range: 1-64, No missing values, Numeric 
#' age            Range: 29-67, No missing values, Numeric 
#' sex            Range: 0-1, No missing values, Numeric 
#' race           Range: 0-1, No missing values, Numeric 
#' diagnosis      No range, No missing values, Character 
#' diagnosis.type Range: 0-1, No missing values, Numeric 
#' time.to.transplant Range: 1.84-173.83, No missing values, Numeric 
#' prior.radiation Range: 0-1, No missing values, Numeric 
#' prior.chemo    Range: 0-8, No missing values, Numeric 
#' prior.transplant Range: 0-1, No missing values, Numeric 
#' recipient.cmv  Range: 0-1, No missing values, Numeric 
#' donor.cmv

**Comment by higgi13425** [comment]
looks like this would work. Pretty good!

**Comment by higgi13425** [comment]
A good first draft, and a big help overall when there are many variables.

**Comment by JamesHWade** [comment]
Awesome! Thank you for sharing! I'm going to close the issue, but I'm happy to debug any new ones that pop up. Thanks again for testing!

**Comment by higgi13425** [comment]
With Summary, likely need to go to more tokens (up to 2000?)

**Comment by MichelNivard** [comment]
@JamesHWade one issue with glimpse is that it gives actual data to OpenAI; hospitals research data compliance officers will have strokes over this... anyway, id' either mark glimpse in bold and red and add a warning  ("PROMPT CONTAINS YOUR DATA, IT WILL BE SEND OFFSITE TO OPENAI") or remove the option.... (this is my academic background making me opinionated...)

**Comment by higgi13425** [comment]
On the plus side, for the {medicaldata} package, all data are deidentified.
Not sure if there is a way to get skimr to work - might have to drop that option

**Comment by higgi13425** [comment]
I agree with Michel's point about glimpse, though if someone is putting identifiable health data into a data package, they already have big problems.

**Comment by JamesHWade** [comment]
Strange... `skimr` was working well for me in testing. I think it's hard to predict which format will work well with these models. I'll remove glimpse from the app. At least summary seems to work.

**Comment by MichelNivard** [comment]
Skimr worked well for me for some datasets, I was primarily concerned for people who use internal data packages, or want too document using these tools without really building packages.

**Comment by MichelNivard** [comment]
@JamesHWade I think what this app misses is a field to enter text/context from outside R, say you have a word doc with a description of the data collection or a section of an article describing the collection; wouldn't it be cool if you could provide the app with 1. the summary of the data frame AND the freeform text for it to generate a data description that distills both?

**Comment by JamesHWade** [comment]
I'm gonna call this closed for now. There's still more work that needs to be done, but it's mostly functional as-is. Please re-open or create a new issues if you want a specific new addition/feature.
