### ISSUE TITLE
Use proxy to access openai for Chinese users?

### ISSUE THREAD

**Issue by kun-ecology** [JamesHWade/gpttools#52]
As a Chinese user, I came across this error when using gpttools:
`! Timeout was reached: [api.openai.com] Resolving timed out after 10012 milliseconds`

I guess it is due to the proxy. I am using Clash and I tried to add the local proxy in .Renviron file following [this](https://community.rstudio.com/t/corporate-proxy-for-rstudio/140609/3), but it still gives me the error.

Thanks in advance and looking forward to your reply!

Best regards
Kun Guo

**Comment by JamesHWade** [comment]
Over in gptstudio, it was solved by allowing a different URL in place of the default openai url. Would that be an option for you?

**Comment by kun-ecology** [comment]
Thanks so much for your reply. 

I guess you are referring to these two issues:
- [Fail to make the connection when I use gptstudio](https://github.com/MichelNivard/gptstudio/issues/116)
- [add a function to set the URL of API KEY](https://github.com/MichelNivard/gptstudio/issues/90). 

However, I did not manage to fix it with them.

Nevertheless, I followed this post [accessing github from behind corporate proxy - RStudio IDE - Posit Community](https://community.rstudio.com/t/accessing-github-from-behind-corporate-proxy/100339/3) and it works now!

The key is to run the following code:
```
Sys.setenv(http_proxy="http://your_proxy_ip:your_proxy_port")
Sys.setenv(http_proxy_user="http://your_proxy_ip:your_proxy_port")
Sys.setenv(https_proxy="http://your_proxy_ip:your_proxy_port")
Sys.setenv(https_proxy_user="http://your_proxy_ip:your_proxy_port")
```

I add these codes to the [.Rprofile.site file](https://support.posit.co/hc/en-us/articles/360047157094-Managing-R-with-Rprofile-Renviron-Rprofile-site-Renviron-site-rsession-conf-and-repos-conf), so I do not need to rerun them for every project.

Perhaps this is not an elegant way to establish the connection via proxy, but it works and I hope it is useful for anyone who comes across the same problem.

Best
Kun

**Comment by JamesHWade** [comment]
@kun-ecology, it looks like you were able to solve the issue, but please reopen if it is not working.

Sorry for the very delayed reply. I've been out on parental leave.
