### ISSUE TITLE
No change to code/text in script when running gpttools functions

### ISSUE THREAD

**Issue by j-kind** [JamesHWade/gpttools#57]
Hello, I'm excited to get started with gpttools but I seem to have run into an issue off the bat. 

I've installed gpttools using pak::pak("JamesHWade/gpttools") which seemed to work fine.

The openai token is set properly in the r_environ and works well with gptstudio.

The gpttools features appear in the addins menu and are available through Ctrl+Shift+P

However, when I try to use any of the gpttools functions something appears to be happening in the console but my script remains unchanged and I can't access the response from OpenAI.
 
I have tried restarting R, reinstalling the package, using a clean environment and various different code chunks and functions (suggest unit tests/suggest improvements/convert to function etc) however no matter what I've done the result has been the same.

This is an example of the output from the console: 

Selection: plantae <- lit_ents %>% filter(kingdom == "Plantae") %>% count() %>% collect() %>% as.numeric()
✔ Received response from OpenAI
Text to insert: plantae <- lit_ents %>% filter(kingdom == "Plantae") %>% count() %>% collect() %>%
as.numeric()

I'm using the latest versions of R (4.3.1) and R Studio (2023.09.0+463)

**Comment by EricMarcon** [comment]
I'm afraid I have the same issue exactly. Is something broken?

Thanks for your efforts.

**Comment by JamesHWade** [comment]
Sorry for the extreme delay, @j-kind. I've been out on parental leave, but I hope to have time to work on the package again soon.

Thank you both for trying it out!

**Comment by JamesHWade** [comment]
I'm just about to merge #59. Please give the latest version a try to see if it's resolved your issue.

You can install it with `pak::pak("jameshwade/gpttools")`.
