### ISSUE TITLE
Leave dependency on openai

### ISSUE THREAD

**Issue by msberends** [JamesHWade/gpttools#9]
Great work, thanks for this initiative!

It seems that the openai package on CRAN is not actually from OpenAI, but just a wrapper package from an OpenAI user. It also seems that there’s not a lot of experience with R development on their side, indicated by how they are struggling to define a correct required R version in DESCRIPTION. No problem of course, but it’s probably not a good idea at the moment to rely on their work. 

So, I would suggest to try to leave the dependency on that package, so there’s no need for users to install your openai fork, and to allow a much wider range of users for your addin package.

**Comment by JamesHWade** [comment]
I'll work on bypassing OpenAI for the short term. If the R>=4.2 dependency is removed, I'd like to use their functions. There's way more error checking build in than I would have done 😆

**Comment by JamesHWade** [comment]
I have some base pipes that I need to remove for older dependency compatibility, but it is no longer dependent on openai (listed in suggests). If someone asks for it, I'll remove the base pipe usage.
